modLoader="javafml"
loaderVersion="[3,)"
license="${mod_license}"

[[mods]]
modId = "immersivetechnology"
version = "${version}"
displayName = "Immersive Technology"
description = "An in development version of Immersive Technology for Minecraft 1.21.1 on NeoForge."
authors = "tgstyle, MagneticPrism"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology"
logoFile = "ITlogo.png"
credits = "tgstyle (author), Peter (new models), MagneticPrism (started the port), KHAZ (new sounds), and the Immersive Engineering Team (code dependencies)"

[[dependencies.immersivetechnology]]
modId="neoforge"
type="required"
versionRange="[${version_neoforge},)"
ordering="NONE"
side="BOTH"

[[dependencies.immersivetechnology]]
modId="minecraft"
type="required"
versionRange="[${version_mc}]"
ordering="NONE"
side="BOTH"

[[dependencies.immersivetechnology]]
modId="immersiveengineering"
type="required"
versionRange="[${version_ie},)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="mixins.immersivetechnology.json"
